In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
with open(r"C:\Users\user\OneDrive - iitkgp.ac.in\Documents\Convolve\train.json") as f:
    data = json.load(f)

In [3]:
data

{' 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.363779 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n': 'normal',
 ' 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.527847 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n': 'normal',
 ' 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.675872 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n': 'normal',
 ' 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.823719 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n': 'normal',
 ' 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.982731 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n': 'normal',
 ' 1117838571 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.51.131467 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n': 'normal',
 ' 1117838571 2005.06.

In [4]:
len(data)

4152659

In [5]:
df = pd.DataFrame(data, index=[0])

In [6]:
df.head()

1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.363779 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n  \
0                                             normal                                                                                                     

   1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.527847 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n  \
0                                             normal                                                                                                     

   1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.675872 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n  \
0                                             normal                                                                                                     

   1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.823719 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n  \
0                                             normal                                                                                                     

   1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.982731 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n  \
0                                             normal                                                                                                     

   1117838571 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.51.131467 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n  \
0                                             normal                                                                                                     

   1117838571 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.51.293532 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n  \
0                                             normal                                                                                                     

   1117838571 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.51.428563 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n  \
0                                             normal                                                                                                     

   1117838571 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.51.601412 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n  \
0                                             normal                                                                                                     

   1117838571 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.51.749199 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n  \
0                                             normal                                                                                                     

   ...  \
0  ...   

  1118545529 2005.06.11 R30-M0-N9-C:J16-U01 2005-06-11-20.05.29.686743 R30-M0-N9-C:J16-U01 RAS KERNEL FATAL data TLB error interrupt  \
0                                           abnormal                                                                                   

  1118545529 2005.06.11 R30-M0-N9-C:J16-U01 2005-06-11-20.05.29.787679 R30-M0-N9-C:J16-U01 RAS KERNEL FATAL data TLB error interrupt  \
0                                           abnormal                                                                                   

  1118545529 2005.06.11 R30-M0-N9-C:J16-U01 2005-06-11-20.05.29.936823 R30-M0-N9-C:J16-U01 RAS KERNEL FATAL data TLB error interrupt  \
0                                           abnormal                                                                                   

  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-06-11-20.05.30.136414 R3

In [7]:
new_df = df.T

In [8]:
new_df.shape


(4152659, 1)

In [9]:
new_df.reset_index(level = 0, inplace = True)


In [10]:
new_df.head()

index       0
0   1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
1   1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
2   1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
3   1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
4   1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal

In [11]:
new_df.shape

(4152659, 2)

In [12]:
df_new2 = new_df.rename(columns = {'index' : 'log', 0: 'result'})

    

In [13]:
df_new2.head()

log  result
0   1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
1   1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
2   1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
3   1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
4   1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal

In [14]:
df_new2[df_new2['result'] == 'normal']

log  result
0         1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
1         1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
2         1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
3         1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
4         1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
...                                                    ...     ...
4082962   1133448452 2005.12.01 R67-M1-NA-C:J05-U11 200...  normal
4082963   1133448452 2005.12.01 R44-M0-ND-C:J15-U11 200...  normal
4082964   1133448452 2005.12.01 R40-M1-N7-C:J04-U11 200...  normal
4082965   1133448452 2005.12.01 R45-M0-N5-C:J04-U01 200...  normal
4082966   1133448452 2005.12.01 R65-M0-N7-C:J17-U01 200...  normal

[4082967 rows x 2 columns]

In [15]:
df_new2.loc[4082967 : ]

log    result
4082967  1117869872 2005.06.04 R23-M1-N8-I:J18-U11 2005...  abnormal
4082968  1117869872 2005.06.04 R04-M1-N4-I:J18-U11 2005...  abnormal
4082969  1117869872 2005.06.04 R04-M1-N4-I:J18-U01 2005...  abnormal
4082970  1117869873 2005.06.04 R35-M1-N0-I:J18-U11 2005...  abnormal
4082971  1117869873 2005.06.04 R35-M1-N0-I:J18-U01 2005...  abnormal
...                                                    ...       ...
4152654  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
4152655  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
4152656  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
4152657  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
4152658  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal

[69692 rows x 2 columns]

In [16]:
df_new2.result.nunique()

2

In [17]:
df_new2.log[0:1]

0     1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...
Name: log, dtype: object

In [18]:
df_new2.head()

log  result
0   1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
1   1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
2   1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
3   1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
4   1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal

Handling Char value

In [19]:
import gensim

In [20]:
review_log = df_new2.log.apply(gensim.utils.simple_preprocess)

In [21]:
review_log

0          [ras, kernel, info, instruction, cache, parity...
1          [ras, kernel, info, instruction, cache, parity...
2          [ras, kernel, info, instruction, cache, parity...
3          [ras, kernel, info, instruction, cache, parity...
4          [ras, kernel, info, instruction, cache, parity...
                                 ...                        
4152654    [ras, kernel, fatal, data, tlb, error, interrupt]
4152655    [ras, kernel, fatal, data, tlb, error, interrupt]
4152656    [ras, kernel, fatal, data, tlb, error, interrupt]
4152657    [ras, kernel, fatal, data, tlb, error, interrupt]
4152658    [ras, kernel, fatal, data, tlb, error, interrupt]
Name: log, Length: 4152659, dtype: object

In [22]:
review_log.shape

(4152659,)

In [23]:
review_log = review_log

In [24]:
review_log.loc[0]


['ras',
 'kernel',
 'info',
 'instruction',
 'cache',
 'parity',
 'error',
 'corrected']

In [25]:
df_new2.log.loc[0]

' 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.363779 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n'

In [26]:
review_log.loc[455667]


['nc',
 'nc',
 'ras',
 'kernel',
 'fatal',
 'guaranteed',
 'data',
 'cache',
 'block',
 'touch']

In [27]:
import nltk
from gensim.models import Word2Vec
from nltk.corpus import stopwords

In [28]:
len(review_log)

4152659

In [29]:
review_log[0]

['ras',
 'kernel',
 'info',
 'instruction',
 'cache',
 'parity',
 'error',
 'corrected']

In [30]:
review_log[0][0]

'ras'

In [31]:
ans = ''
for i in review_log[0]:
    ans = ans+ ' '+ i
print(ans)
    
    
    
  

 ras kernel info instruction cache parity error corrected


In [32]:
corpus = []
for i in range(0,len(review_log)):
    ans = ''
    for j in review_log[i]:
        ans = ans+ ' '+ j
    corpus.append(ans)
        
    

    
    

In [33]:
corpus[-1]

' ras kernel fatal data tlb error interrupt'

In [35]:
len(corpus)

4152659

In [36]:
corpus[0:4]

[' ras kernel info instruction cache parity error corrected',
 ' ras kernel info instruction cache parity error corrected',
 ' ras kernel info instruction cache parity error corrected',
 ' ras kernel info instruction cache parity error corrected']

In [37]:
import tensorflow as tf

In [38]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [39]:
voc_size=5000

In [40]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],
 [806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],
 [806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],
 [806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],
 [806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],
 [806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],
 [806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],
 [806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],
 [806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],
 [806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],
 [806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],
 [806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],
 [806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],
 [806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],
 [806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],
 [806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],
 [806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],
 [806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],
 [806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],
 [806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],


In [44]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)


[[   0    0    0 ... 1939 3123 3506]
 [   0    0    0 ... 1939 3123 3506]
 [   0    0    0 ... 1939 3123 3506]
 ...
 [   0    0    0 ... 2101 3123 2194]
 [   0    0    0 ... 2101 3123 2194]
 [   0    0    0 ... 2101 3123 2194]]


In [45]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,  806, 1242, 3879, 4182, 2085, 1939, 3123, 3506])

In [46]:
embedding_vector_features=45
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 45)            225000    
                                                                 
 lstm_1 (LSTM)               (None, 100)               58400     
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 283,501
Trainable params: 283,501
Non-trainable params: 0
_________________________________________________________________
None


In [79]:

from tensorflow.keras.layers import Dropout
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Dropout(0.2))
model1.add(LSTM(100))
model1.add(Dropout(0.2))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 20, 40)            200000    
                                                                 
 dropout_4 (Dropout)         (None, 20, 40)            0         
                                                                 
 lstm_3 (LSTM)               (None, 100)               56400     
                                                                 
 dropout_5 (Dropout)         (None, 100)               0         
                                                                 
 dense_3 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [60]:
from sklearn.model_selection import train_test_split
x_train,x_text,y_train,y_text = train_test_split(X_final, y_final, test_size = 0.3, random_state = 42)

In [61]:
x_train.shape

(2906861, 20)

In [64]:
x_text.shape

(1245798, 20)

In [65]:
### Finally Training
model.fit(x_train,y_train,epochs=2,batch_size=64,validation_data=(x_text, y_text))

Epoch 1/2
45420/45420 [==============================] - 1284s 28ms/step - loss: 6.7597e-06 - accuracy: 1.0000 - val_loss: 1.7875e-05 - val_accuracy: 1.0000
Epoch 2/2
45420/45420 [==============================] - 1553s 34ms/step - loss: 2.0730e-06 - accuracy: 1.0000 - val_loss: 3.5065e-05 - val_accuracy: 1.0000


In [66]:
y_pred = model.predict(x_text)

38932/38932 [==============================] - 253s 6ms/step


In [69]:
y_pred

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)

In [73]:
from sklearn.metrics import classification_report
classification_report(y_text, result1)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00     20796\n           1       1.00      1.00      1.00   1225002\n\n    accuracy                           1.00   1245798\n   macro avg       1.00      1.00      1.00   1245798\nweighted avg       1.00      1.00      1.00   1245798\n'

In [70]:
B = np.where(y_pred > 0.5, 1, 0)

In [71]:
B

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]])

In [72]:

result1 = B.flatten()

In [47]:
len(embedded_docs)

4152659

In [48]:
y=pd.get_dummies(df_new2['result'])
y=y.iloc[:,1].values

In [49]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=uint8)

In [50]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=uint8)

In [51]:
y.shape

(4152659,)

In [52]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,  806, 1242, 3879, 4182, 2085, 1939, 3123, 3506])

In [53]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [54]:
### Finally Training
model.fit(X_final,y_final,epochs=2,batch_size=64)

Epoch 1/2
64886/64886 [==============================] - 1776s 27ms/step - loss: 3.3168e-04 - accuracy: 0.9999
Epoch 2/2
64886/64886 [==============================] - 1829s 28ms/step - loss: 1.2380e-05 - accuracy: 1.0000


In [80]:
### Finally Training with dropout layers
model1.fit(X_final,y_final,epochs=2,batch_size=128)

Epoch 1/2
32443/32443 [==============================] - 1518s 47ms/step - loss: 5.6876e-04 - accuracy: 0.9999
Epoch 2/2
32443/32443 [==============================] - 4459s 137ms/step - loss: 1.8096e-05 - accuracy: 1.0000


In [74]:
test_data = pd.read_csv(r"C:\Users\user\OneDrive - iitkgp.ac.in\Documents\Convolve\test.csv",sep = ',',  delimiter=None, 
                header='infer', names=None, index_col=None, usecols=None, squeeze=False, engine='python')

C:\Users\user\AppData\Local\Temp\ipykernel_3452\3988210464.py:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  test_data = pd.read_csv(r"C:\Users\user\OneDrive - iitkgp.ac.in\Documents\Convolve\test.csv",sep = ',',  delimiter=None,


In [75]:
test_data.columns

Index(['ID', ' Log'], dtype='object')

In [76]:
review_log_test = test_data[' Log'].apply(gensim.utils.simple_preprocess)

In [77]:
corpus_test = []
for i in range(0,len(review_log_test)):
    an = ''
    for j in review_log_test[i]:
        an = an+ ' '+ j
    corpus_test.append(an)
        

In [78]:
onehot_repr1=[one_hot(words,voc_size)for words in corpus_test] 
onehot_repr1

[[806, 1242, 343, 2331, 1242, 4, 4549, 2526],
 [806, 1242, 343, 3812, 2101, 3123, 2194],
 [806, 1242, 343, 3812, 2101, 3123, 2194],
 [806, 1242, 3879, 501, 3097],
 [806, 1242, 343, 3812, 2101, 3123, 2194],
 [806, 1242, 3879, 2653, 4378, 1345, 919, 1589],
 [806, 1242, 343, 3812, 2101, 3123, 2194],
 [806, 1242, 3879, 501, 3097],
 [806, 1242, 343, 3812, 2101, 3123, 2194],
 [806, 1242, 3879, 409, 3979, 4514, 4192, 2578, 2393],
 [806, 1242, 3879, 501, 3097],
 [806, 1242, 3879, 4182, 2085, 1939, 3123, 3506],
 [806, 1242, 343, 3812, 2101, 3123, 2194],
 [806, 1242, 3879, 501, 3097],
 [806, 1242, 343, 3812, 2101, 3123, 2194],
 [4421, 4421, 806, 1242, 3879, 501, 3097],
 [806, 1242, 343, 3812, 2101, 3123, 2194],
 [806, 1242, 343, 3812, 2101, 3123, 2194],
 [806,
  3301,
  343,
  409,
  395,
  1769,
  4475,
  3979,
  4997,
  1974,
  946,
  4650,
  2544,
  2652,
  1769],
 [806, 1242, 343, 3812, 2101, 3123, 2194],
 [523, 523, 806, 1242, 3879, 501, 3097],
 [2591, 2591, 806, 1242, 3879, 501, 3097],
 [8

In [79]:
sent_length=20
embedded_docs1=pad_sequences(onehot_repr1,padding='pre',maxlen=sent_length)
print(embedded_docs1)

[[   0    0    0 ...    4 4549 2526]
 [   0    0    0 ... 2101 3123 2194]
 [   0    0    0 ... 2101 3123 2194]
 ...
 [   0    0    0 ... 2101 3123 2194]
 [   0    0    0 ... 2101 3123 2194]
 [   0    0    0 ... 3879  501 3097]]


In [80]:
X_final_test=np.array(embedded_docs1)

In [81]:
y_pred1=model.predict(X_final_test)

18604/18604 [==============================] - 290s 16ms/step


In [124]:
y_pred1

array([[9.999956e-01],
       [5.231645e-08],
       [5.231645e-08],
       ...,
       [5.231645e-08],
       [5.231645e-08],
       [1.000000e+00]], dtype=float32)

In [125]:
y_pred1.shape

(595300, 1)

In [126]:
B = np.where(y_pred1 > 0.5, 1, 0)

In [127]:
B

array([[1],
       [0],
       [0],
       ...,
       [0],
       [0],
       [1]])

In [128]:

result = B.flatten()

In [129]:
result

array([1, 0, 0, ..., 0, 0, 1])

In [130]:
results = result.tolist()

In [131]:
import numpy as np
a = np.array(results, dtype = 'object')
labels = [ "abnormal", "normal" ]

for i in range(len(labels)):
        a[a == i] = labels[i]
print(a)

['normal' 'abnormal' 'abnormal' ... 'abnormal' 'abnormal' 'normal']


In [132]:
final_df = pd.DataFrame(a,columns=[" Label"])
final_df["ID"] = final_df.index 
columns_titles = ["ID"," Label"]
final_df=final_df.reindex(columns=columns_titles)
final_df.head()

ID     Label
0   0    normal
1   1  abnormal
2   2  abnormal
3   3    normal
4   4  abnormal

In [133]:
import os
os.getcwd()

'C:\\Users\\user'

In [134]:
final_df.to_csv('convolve_r3.csv', index=False)